Added MainActivity, Hello World and config at AndroidManifest.xml
Elitma-Dev/ToKing pull request #5
Opened 2020-08-12 21:43 UTC by georgebaronheid

2020-08-12 22:14 UTC, sp4wna1 commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
Não está no padrão.

2020-08-12 22:15 UTC, sp4wna1 requested changes

2020-08-12 22:15 UTC, sp4wna1 commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
Não está no padrão.

2020-08-12 22:15 UTC, sp4wna1 commented on app/src/main/java/br/com/prado/toking/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
Agora é possivel adicionar o R.layout.activity_main, direto no construtor do AppCompatActivity, assim vc n precisa sobrescrever o oncreate.

2020-08-13 01:22 UTC, georgebaronheid commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
Fixed

2020-08-13 01:22 UTC, georgebaronheid commented on app/src/main/java/br/com/prado/toking/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
Fixed

2020-08-13 03:27 UTC, sp4wna1 approved these changes

2020-08-13 03:27 UTC, merged