Added Swipe Fuctionalities
Elitma-Dev/ToKing pull request #9
Opened 2020-08-20 20:23 UTC by georgebaronheid

2020-08-21 20:39 UTC, sp4wna1 approved these changes

2020-08-21 20:39 UTC, sp4wna1 commented on app/src/main/java/br/com/prado/toking/MainActivityAdapter.kt
> +        binding.activityMainViewPager.registerOnPageChangeCallback(object :
Toda vez que o método createFragment for requisitado pelo ViewPager2 (ou seja, toda vez que você alterar de aba) ele irá adicionar esses listeners ao viewPager.
Esse método está fazendo muito mais do que deveria. O nome dele é createFragment e ele retorna um Fragment. Esse é a sua função.

O adapter não deveria conhecer o binding da Activity, pois essas regras são regras de VIEWS e não de adapters.

2020-08-21 20:39 UTC, sp4wna1 requested changes
Precisa corrigir o adapter

2020-08-21 22:47 UTC, sp4wna1 requested changes

2020-08-21 22:47 UTC, sp4wna1 commented on app/src/main/java/br/com/prado/toking/MainActivity.kt
> +    private lateinit var viewPager: ViewPager2
Remover essa var

2020-08-24 12:17 UTC, georgebaronheid commented on app/src/main/java/br/com/prado/toking/MainActivity.kt
> +    private lateinit var viewPager: ViewPager2
Done

2020-08-24 12:35 UTC, georgebaronheid commented on app/src/main/java/br/com/prado/toking/MainActivityAdapter.kt
> +        binding.activityMainViewPager.registerOnPageChangeCallback(object :
Done

2020-08-24 12:37 UTC, sp4wna1 approved these changes
Boa

2020-08-24 12:46 UTC, merged